### ISSUE TITLE
SDL Error:  Window data not set,  on trying out the examples using the instruction on readme.md

### ISSUE THREAD

**Issue by Inc0n** [bufferswap/ViralityEngine#25]
I uses Mac m1 OSX, sbcl 2.2.9.

The instructions used exactly:
```
(ql:register-local-projects)
(ql:quickload :virality-examples)
(in-package :virality-examples)
```
Now start any of the example will trigger the following errors:
```
SDL Error: Window data not set
   [Condition of type SDL2::SDL-ERROR]

Backtrace:
  0: (SDL2:CREATE-WINDOW :TITLE "Virality Engine" :X :CENTERED :Y :CENTERED :W 1920 :H 1080 :FLAGS (:OPENGL))
  1: (V::MAKE-DISPLAY #<V::CORE {700A48A393}>)
  2: (V::INITIALIZE #<V::CORE {700A48A393}> :VIRALITY-EXAMPLES (("damaged-helmet-turn-table" EXAMPLES)))
  3: (V:START :PROJECT :VIRALITY-EXAMPLES :SCENE (("damaged-helmet-turn-table" EXAMPLES)))
```
After sldb-quit on this error, the following pops up:
```
The slot VIRALITY::%INPUT-DATA is unbound in the object
#<CORE {700A48A393}>.
   [Condition of type UNBOUND-SLOT]

Backtrace:
  0: ((:METHOD SLOT-UNBOUND (T T T)) #<unused argument> #<V::CORE {700A48A393}> V::%INPUT-DATA) [fast-method]
  1: (SB-PCL::SLOT-UNBOUND-INTERNAL #<V::CORE {700A48A393}> 8)
  2: (V::SHUTDOWN-GAMEPADS #<V::CORE {700A48A393}>)
  3: (V::DEINITIALIZE #<V::CORE {700A48A393}>)
  4: ((FLET "CLEANUP-FUN-0" :IN V:START)) [cleanup]
  5: (V:START :PROJECT :VIRALITY-EXAMPLES :SCENE (("damaged-helmet-turn-table" EXAMPLES)))
```

**Comment by Inc0n** [comment]
I thought it could be because of how OSX behaves slightly differenetly, so I tried it again with `trivial-main-thread:with-body-in-main-thread`. Now no more of that error, but nothing pops out either.

**Comment by psilord** [comment]
Unfortunately, we developers don't have access to an Mac M1 machine so we can't really debug and fix the problem.

If you try running SBCL in a console, and not in SLIME/SLY, and then try your initial procedure again, it might work. Apple likes changing their threading API quite often and it causes these sorts of problems.  You can try finding us on IRC at #bufferswap on irc.libera.chat and we might be able to provide interactive help to resolve the problem.

**Comment by Inc0n** [comment]
Thanks for the detailed info. That is unfortunate, indeed, I think I next step is to get laptop capable of smooth linux experience...
