### ISSUE TITLE
Error loading virality-examples

### ISSUE THREAD

**Issue by psvensson** [bufferswap/ViralityEngine#26]
Hi, I am using Linux mint 22 and SBCL 2.0.1 and I am very much a Lisp newbie.
I am trying to follow the instruction on how to load the examples (any at all) and run into a problem.

I have created ~/quicklisp/local-projects and cloned out the ViralityEngine project as I should, then checkout the develop branch.

However, when I then follow the instruction in the readme I get; "System "virality-examples" not found";

![image](https://user-images.githubusercontent.com/39554/200641264-4d968750-253d-494b-a194-654554e0f730.png)

**Comment by psvensson** [comment]
OK, so I used a trick I found elsewhere to include the current directory in the local-projects, and did this;

(ql:quickload :virality-examples)

After that, I could run quickload, et.c. and eventually to start the list of examples and get the helmet up and spinning. Nice stuff! :)   So closing this then.

**Comment by psilord** [comment]
I'm glad you got it working! Thank you for trying it!

This is a strange edge case that I cannot reproduce and very occasionally people hit it. I added the `(ql:register-local-projects)` line to try and get QL to recognize the newly checked out system and this seemed a well educated guess. But it appears this odd edge case still happens. 

I've done the README procedure and others have too and have been successful, so I'm not quite sure where the disconnect with QL and the directions is... I'll keep an eye on it!

**Comment by psvensson** [comment]
OK, thx! Here is one other thing I forgot to mention - the first time I managed to get quickload to run, it did a whole lot of compiling, many many lines of dots and compiler output, then the running of the examples failed. When I quite sbcl and started it again and reran the sequence, it did work.

I'm sorry I don't have a detailed output, but perhaps there are two issues (possibly only linux-related);
1. The current directory does not reliably get added to the path quicklisp can find systems in
2. There might be a timing problem in the compile step, so that things compiled to not appear as ready (I think remember that it complained about not finding the 'examples' directory, when trying to run them directly.
3. 
Not sure if this confuses more than it helps, but hope it might be of some use at least
