### ISSUE TITLE
Being able to use material defined inside glb file

### ISSUE THREAD

**Issue by psvensson** [bufferswap/ViralityEngine#27]
Hi, I've been able to add a new example to try to display other models. This is what I've (admittedly quite sloppily, but just for testing) add to the file example-matcap.lisp, since it already contained examples that loaded models, which I could peruse.

```
(v:define-prefab "default-entity" (:library examples)
  "A base description of the damaged helmet so we can use it easily elsewhere."
  (comp:transform :rotate (q:orient :local :x o:pi/2))
  (comp:mesh :asset '(meshes palladin7)
             :name "FloorFlat") ;; 001 to 024
  ;; TODO: When this material name is nonexistant, it doesn't draw anything.
  (comp:render :material 'matcap-lookup
               :slave (v:ref :self :component 'comp:mesh)))

(v:define-prefab "Entity01" (:library examples)
  (("camera" :copy "/cameras/perspective")
   (comp:camera (:policy :new-args)))

  (("Entity01" :copy "/default-entity")
   (comp:transform :scale 01f0  :translate (v3:vec -15f0 -60f0 -80f0))
   (comp:sphere :on-layer :ground)
   (simple-mouse-rotator :clamp-p t)))
```

The code is completely copied fro existing code, except for referring to a new model I put in the example meshes directory.

And it works!

However, since the model logic have separate steps for referring to the mesh and the material, I am now reusing material for another model in the examples, which doesn't look right, of course. The material for the model I want to show is included in the gltf/glb file that is loaded. Is there any simple way to make the prefab default to load material from inside the mesh/model/glb file if no other materials are declared?

If not (and I suppose not) could you give hints as to where one would do this?

**Comment by mfiano** [comment]
Hello @psvensson!The short answer: no there is not. Only mesh data is extracted from a GLTF format in Virality. This has been discussed, and actually has a stale branch integrating models with meshes better, but our priorities have shifted a bit on the engine. 

Additionally, we all took about a 1.5 year break from the project, and are just now slowing getting back into things. With that said, we have monthly screen sharing conferences, and the next one will be on this Saturday. You are definitely more than free to join, and maybe we can give you some better answers and some screen-sharing examples of what to do to fix it.

If you want to talk to the team more directly, you can join the Libera IRC channel `#bufferswap`, or email me (from my profile page).

**Comment by psilord** [comment]
There is a mostly completed GLTF reader for Virality, but it needs to be finished and integrated with the define-prefab DSL. I will close this ticket since it is on our agenda to perform this work, but it might not get completed for a little while.
