### ISSUE TITLE
Examples won't load "The function VIRALITY:SETUP-REPL is undefined" 

### ISSUE THREAD

**Issue by Ecsodikas** [bufferswap/ViralityEngine#99]
Hi, I'm currently trying to run the examples and I followed the steps in the README.md. 
The it looks like the setup-repl function does not exist in the current development branch, or am I missing a step here?

```
* (ql:quickload :virality-examples)
To load "virality-examples":
  Load 1 ASDF system:
    virality-examples
; Loading "virality-examples"

(:VIRALITY-EXAMPLES)
* (in-package :virality-examples)
#<PACKAGE "VIRALITY-EXAMPLES">
* (virality:start)

debugger invoked on a UNDEFINED-FUNCTION @54600904 in thread
#<THREAD tid=30835 "main thread" RUNNING {1001140093}>:
  The function VIRALITY::SETUP-REPL is undefined.
```

Thanks for the nice work and thanks in advance!

**Comment by psilord** [comment]
Hello!

How are you running those snippets? In emacs with SLY or SLIME? Or on the command line SBCL interface? etc.

I was able to reproduce it using the SBCL command line interface in the terminal. Usually we develop Virality in 
Emacs with SLY (or less oftem SLIME) and this code seems to fail when run at the raw SBCL repl.

I'll take a look!

Thank you!

**Comment by Ecsodikas** [comment]
You are right. I ran it in the terminal using the SBCL interface. When running from SLY it runs flawlessly. Thanks for the pointer. I'll check out the engine a bit more, looks pretty good so far. Thanks for the hard work and fast answer!

**Comment by psilord** [comment]
Sure no problem! I'll take a look at that problem and maybe fix it anyways cause the engine should be able to be startable form the command line too.

The engine is still in a nascent form and we know there will be some serious changes to it as it evolves (for example, adding multipass rendering and reworking the component flow). Currently we're doing some work in the engine breaking it into layers and reworking how app data is managed in the engine so we can work on more new features concurrently. 

The Protect the Planets example is a tiny game we wrote with it to test out the engine. If you have an xbox-like controller it should mostly work out of the box.

If you have more questions (well, you will, cause our documentation is mostly missing!), let us know!

**Comment by psilord** [comment]
Ok I fixed it and pushed to develop. It should work in Emacs with SLY/SLIME and also at the command line. The missing feature at the command line is that the repl is not available to live code in the engine. There are ways to make this work
but we just haven't done them since it is an uncommon development environment for us.

Thank you!
